# name: Build and Release Binary
on: push
name: Build and release on push
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        run: go build -v ./...

      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: vault/plugins/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# on:
#   release:
#     types: [created]

# jobs:
#   build:
#     name: Build and test
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2

#     - name: Set up Go
#       uses: actions/setup-go@v2
#       with:
#         go-version: 1.15

#     - name: Build
#       run: go build -v ./...

#     - name: Test
#       run: go test -v ./...

#   publish:
#     name: Create release-artifacts
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up Go
#         uses: actions/setup-go@v2
#         with:
#           go-version: 1.15

#       - name: Build
#         run: go build -v ./...

#       - name: Upload the artifacts
#         uses: skx/github-action-publish-binaries@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           args: './vault/plugins/*'
